title: "Niccole Porras"
description: "My personal academic webpage"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/